import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Providers from "@/lib/Providers";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Memorial",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {
  const locale = await getLocale();

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider  messages={messages}>
        <Providers>
          <Toaster position="top-center" />
          <AntdRegistry>{children}</AntdRegistry>
        </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
